### ISSUE TITLE
Cannot romanize '앞만'

### ISSUE THREAD

**Issue by sgalal** [osori/korean-romanizer#3]
```
>>> from romanizer import Romanizer
>>> Romanizer('앞만').romanize()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "romanizer.py", line 292, in romanize
    _romanized += onset[s.initial] + vowel[s.medial] + coda[s.final]
KeyError: 'ᇁ'
```

**Comment by osori** [comment]
Fixed

**Comment by osori** [comment]
Thank you very much for opening an issue on this! Just updated the repo with a temporary fix while I look into this problem more deeply.
