### ISSUE TITLE
Attempting to romanise '좋아하고 있어요' throws a ValueError

### ISSUE THREAD

**Issue by arg274** [osori/korean-romanizer#9]
### Specs:
 - **OS:** Windows 10 x86_64
 - **Python Version:** 3.8.2

### Current output:
```
>>> from korean_romanizer.romanizer import Romanizer
>>> Romanizer('좋아하고 있어요').romanize()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\Redacted\AppData\Local\Programs\Python\Python38\lib\site-packages\korean_romanizer\romanizer.py", line 105, in romanize
    pronounced = Pronouncer(self.text).pronounced
  File "C:\Users\Redacted\AppData\Local\Programs\Python\Python38\lib\site-packages\korean_romanizer\pronouncer.py", line 23, in __init__
    self.pronounced = ''.join([ str(c) for c in self.final_substitute()])
  File "C:\Users\Redacted\AppData\Local\Programs\Python\Python38\lib\site-packages\korean_romanizer\pronouncer.py", line 102, in final_substitute
    next_syllable.initial = next_syllable.final_to_initial(syllable.final)
  File "C:\Users\Redacted\AppData\Local\Programs\Python\Python38\lib\site-packages\korean_romanizer\syllable.py", line 55, in final_to_initial
    idx = unicode_compatible_finals.index(char)
ValueError: None is not in list
```

**Comment by s67112** [comment]
This seems to be the case for ㅎ final + ㅇ initial combination

**Comment by osori** [comment]
> This seems to be the case for ㅎ final + ㅇ initial combination

Yes, I also think this is the case, probably similar to #10 that you reported. Thank you so much for pointing this out, and I will have a fix available soon!

**Comment by osori** [comment]
'ㅎ' in final is silenced if the initial of the next syllable is ㅇ, and I used `None` to represent a silenced final. The previous implementation did not take about the `None` finals into account, and I pushed a fix that handles them appropriately. Thank you for reporting this issue! (and sorry for taking such a long time.)
